version: "3.8"
services:
  postgredb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: burhan
      POSTGRES_PASSWORD: burhan123
      POSTGRES_DB: financial_system